<?php
/** Red Framework Controller
 * Generated By Red Analytics
 *
 * Date: 10/01/2020
 * Time: 13:44:05
 * @author RedCoder, RT3N
 */

namespace App\Controllers;


use GuzzleHttp\Client;
use GuzzleHttp\Exception\BadResponseException;
use Red\Base\Controller;

class DatabaseController extends Controller
{
    private $api_service;
    private $connection;
    protected $data;

    public function __construct()
    {
        parent::__construct();
        $this->api_service = "http://api.guardiran.org/cloudhound/";
        $headers = ["content-type" => "application/json;charset=UTF-8",
            "API" => "guardiran"];
        $this->connection = new Client(['base_uri' => $this->api_service, 'headers' => $headers]);
    }

    public function databaseStatus()
    {

        try {
            $this->data = $this->connection->request('GET', "v1/database-status/");
        } catch (BadResponseException $e) {
            $this->data = "false";
        }


        if ($this->data == "false") {
            return false;
        } else {
            $this->data = $this->data->getBody();
            $this->data = json_decode($this->data, true);
            return $this->data;
        }
    }

    public function infiniteDatabase($hostname, $ip, $subdomain = null)
    {

        if ($subdomain == null) {
            try {
                $this->connection->request('GET', "v1/infinity/" . $hostname . "/" . $ip);
            } catch (BadResponseException $e) {
            }
        } else {
            try {
                $this->connection->request('GET', "v1/infinity/" . $hostname . "/" . $ip . "/" . $subdomain);
            } catch (BadResponseException $e) {
            }
        }

    }

}