<?php
/** Red Framework Controller
 * Generated By Red Analytics
 *
 * Date: 07/01/2020
 * Time: 09:13:22
 * @author RedCoder, RT3N
 */

namespace App\Controllers;


use GuzzleHttp\Client;
use GuzzleHttp\Exception\BadResponseException;
use GuzzleHttp\Exception\ConnectException;
use Red\Base\Controller;

class DNSHistoryController extends Controller
{

    private $api_service;
    private $connection;
    private $connection_status;
    protected $data;

    public function __construct()
    {
        parent::__construct();
        $this->api_service = "http://api.guardiran.org/cloudhound/";
        $this->connection = new Client(['base_uri' => $this->api_service]);
    }

    public function DNSHistory($hostname){

        $headers = ["content-type" => "application/json;charset=UTF-8",
            "API" => "guardiran"];


        try {
            $this->data = $this->connection->request('GET', "v1/dns-history/" . $hostname,
                ['headers' => $headers]);
        } catch (BadResponseException $e) {
            $this->data = "false";
        }  catch (ConnectException $e){
            $this->data = "false";
            $this->connection_status = false;
        }

        if ($this->connection_status === false) {
            return "Connection Error";
        }

        $this->connection_status = true;



        if ($this->data == "false") {
            return false;
        } else {
            $this->data = $this->data->getBody();
            $this->data = json_decode($this->data, true);
            return $this->data;
        }

    }

    /**
     * @return mixed
     */
    public function getConnectionStatus()
    {
        return $this->connection_status;
    }

}