<?php
/** Red Framework Controller
 * Generated By Red Analytics
 *
 * Date: 06/01/2020
 * Time: 22:11:20
 * @author RedCoder
 */

namespace App\Controllers;


use Red\Base\Controller;

class HelpController extends Controller
{
    public function help()
    {
        echo("\e[1;36;40m
        
        ____ _  _ ____ ____ ___  _ ____ ____ _  _ 
        | __ |  | |__| |__/ |  \ | |__/ |__| |\ | 
        |__] |__| |  | |  \ |__/ | |  \ |  | | \| 
                                                  

       
        CloudHound is a CloudFlare ByPass Tool which is Using Several Methods such 
        
        as DNS History Check, SSL Certificate Check , Cross-Site Port Attack and Etc
         
        to Detect Original Server IP .
        
        Version : \e[1;31;40m1.0.0  
        
        \e[1;36;40mLicense : \e[1;31;40mGPL 3 
                                           
                
        \e[1;36;40mWe Are GuardIran Security Team !
        
        https://guardiran.org
        
        Credits : \e[1;31;40mRedCoder, RT3N
        
        \e[1;37;40m
        
        ~~ Cheat Sheet ~~
        
        \e[1;31;40m[*] Detect Original IP Address of A Server :
        
            [+] \e[1;36;40mdetect guardiran.org
            
        \e[1;31;40m[*] Whois LookUp :
        
            [+] \e[1;36;40mwhois guardiran.org
        
        \e[1;37;40m
        ");
    }

}