<?php
/** Red Framework Controller
 * Generated By Red Analytics
 *
 * Date: 10/01/2020
 * Time: 09:58:22
 * @author RedCoder, RT3N
 */

namespace App\Controllers;


use Red\Base\Controller;

class ProtectionController extends Controller
{


    public static function cloudFlareIP($IP)
    {
        $whois_handler = new WhoisController();
        $whois_handler->fetchData($IP);
        $organization = $whois_handler->getOrganization();

        if ($organization == "Cloudflare, Inc.") {
            return true;
        } else if($organization === false){
            return "private_ip";
        } else {
            return false;
        }
    }

    public static function cloudFlareDNS($dns)
    {
        $cloud_flare_domain = "cloudflare.com";
        $ns = substr($dns, -14, 14);

        if ($ns == $cloud_flare_domain) {
            return true;
        } else {
            return false;
        }

    }

}