<?php
/** Red Framework Model
 * Generated By Red Analytics
 * 
 * Date: 10/01/2020
 * Time: 09:55:44
 * @author RedCoder, RT3N
 */

namespace App\Models;


use Red\Base\Model;

class SubDomainModel extends Model
{
    public function fetchSubDomainList(){

        $this->setFields([
            'subdomain' => 'any',
        ]);

        $this->query("subdomains", READ, DB3);

        return $this->getContent(DB3);

    }

}